tasks:
  - name: yarn install
    init: >
      yarn install &&
      gp sync-done yarn
  - name: nest-1
    init: gp sync-await yarn
    command: npx nx serve nest-1
  - name: nest-2
    init: gp sync-await yarn
    command: npx nx serve nest-2
  - name: react-1
    init: gp sync-await yarn
    command: npx nx serve react-1

ports:
  - port: 3333
  - port: 3334
  - port: 4200
